# Generated by Django 3.2 on 2021-07-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField(default=10)),
                ('light_intensity', models.FloatField(default=0)),
                ('air_temp', models.FloatField(default=0)),
                ('soil_temp', models.FloatField(default=0)),
                ('time', models.CharField(default=0, max_length=30)),
            ],
        ),
    ]
